name: Docker Image For Production
on: 
  push:
    branches:
      - stage
env:
  PROJECT_ID: capable-range-455705-h4
  GAR_LOCATION: asia-northeast3
  REPOSITORY: looper
  SERVICE: chatbot-ai
  REGISTRY: asia-northeast3-docker.pkg.dev/capable-range-455705-h4/looper
  IMAGE_NAME: ai-summary
  VERSION: ${{ github.sha }}

jobs:
  package:
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/stage' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write 
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} \
                       -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .
                       
      - name: Publish container image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest